name: Build KivyMD APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          unzip \
          zip \
          openjdk-17-jdk \
          python3-pip \
          python3-dev \
          python3-setuptools \
          python3-venv \
          python3-distutils \
          libssl-dev \
          libffi-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libfreetype6-dev \
          libgl1-mesa-dev \
          libgles2-mesa-dev \
          libdrm-dev \
          libxkbcommon-dev \
          libxrandr-dev \
          libxss-dev \
          libgconf-2-4 \
          libxtst6 \
          libxrender1 \
          libfontconfig1 \
          libdbus-1-3 \
          libgtk-3-0 \
          libxslt-dev \
          zlib1g-dev \
          libjpeg-dev \
          libtiff-dev \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          libfreetype6-dev
          
    - name: Setup Java Environment
      run: |
        echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
        echo "/usr/lib/jvm/java-17-openjdk-amd64/bin" >> $GITHUB_PATH
        
    - name: Verify Java Installation
      run: |
        java -version
        javac -version
        echo "JAVA_HOME: $JAVA_HOME"
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel
        pip install buildozer cython==0.29.36
        pip install kivy kivymd
        
    - name: Create necessary directories
      run: |
        mkdir -p ~/.buildozer
        mkdir -p .buildozer
        
    - name: Setup Buildozer
      run: |
        buildozer --version
        
    - name: Cache Buildozer global directory
      uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-global-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-global-
          
    - name: Cache Buildozer directory
      uses: actions/cache@v4
      with:
        path: .buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-
          
    - name: Verify project files
      run: |
        echo "Project structure:"
        find . -name "*.py" -o -name "*.kv" -o -name "*.jpg" -o -name "*.png" | head -20
        echo "Main files:"
        ls -la main.py main.kv Prof.jpg 2>/dev/null || echo "Some files missing"
        
    - name: Build APK
      env:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
        ANDROID_HOME: /home/runner/.buildozer/android/platform/android-sdk
        ANDROID_SDK_ROOT: /home/runner/.buildozer/android/platform/android-sdk
        PATH: /usr/lib/jvm/java-17-openjdk-amd64/bin:$PATH
      run: |
        buildozer android debug
        
    - name: List build output
      run: |
        echo "Build directory contents:"
        ls -la bin/ 2>/dev/null || echo "No bin directory"
        find . -name "*.apk" -type f 2>/dev/null || echo "No APK files found"
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kivymd-app-debug
        path: bin/*.apk
        if-no-files-found: warn
        
    - name: Upload build logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          .buildozer/android/platform/build-*/logs/
          .buildozer/android/platform/python-for-android/
        if-no-files-found: ignore
